### ISSUE TITLE
No module named builtins

### ISSUE THREAD

**Issue by atimon** [normyx/MMM-Facial-Recognition-OCV3#29]
When i run capture.py i get the following error: 

> Traceback (most recent call last):
>   File "tools.capture.py", line 9, in <module>
>     from lib.tools.capture import ToolsCapture
>   File "/home/pi/MagicMirror/modules/MMM-Facial-Recognition-OCV3/lib/tools/capture.py", line 10, in <module>
>     from   builtins import input
> ImportError: No module named builtins
>

**Comment by Shebsa** [comment]
Having the same issue here, built opencv 3.4 instead of 3.3.3 because 3.3.3 branch is not there any more if that makes any difference.

**Comment by Shebsa** [comment]
Oh never mind, solved it by applying the fix in the pull request and then running `sudo apt-get install python-future` instead of using the future from pip.
