### ISSUE TITLE
No module named cv2

### ISSUE THREAD

**Issue by Daseca** [normyx/MMM-Facial-Recognition-OCV3#8]
Hello,

i have a problem with this module. All went well till i came to the point where i have to run the 

`python tools.capture.py`

I always run into the error

`pi@raspberrypi:~/MagicMirror/modules/MMM-Facial-Recognition-OCV3 
$ python tools.capture.py
Traceback (most recent call last):
  File "tools.capture.py", line 9, in <module>
    from lib.tools.capture import ToolsCapture
  File "/home/pi/MagicMirror/modules/MMM-Facial-Recognition-OCV3/lib/tools/capture.py", line 16, in <module>
    import cv2
ImportError: No module named cv2
`

Do you have any clues to fix this? Thanks!

**Comment by Jacob12138xieyuan** [comment]
same issue

**Comment by MuhammadJamee** [comment]
your OPENCV is not properly installed. 
Try start terminal - Python > import cv2 (see if there is an error or not)

**Comment by nischi** [comment]
have the same issue and i get an error "ModuleNotFoundError: No module named 'cv2'" if i try import cv2
