### ISSUE TITLE
Capture and Train the model problem

### ISSUE THREAD

**Issue by boomza19193** [normyx/MMM-Facial-Recognition-OCV3#9]
When i run `python tools.capture.py.` on python 3.4.2
it's show error 

> Traceback (most recent call last):
  File "/home/pi/MagicMirror/modules/MMM-Facial-Recognition-OCV3/tools.capture.py", line 9, in <module>
    from lib.tools.capture import ToolsCapture
  File "/home/pi/MagicMirror/modules/MMM-Facial-Recognition-OCV3/lib/tools/capture.py", line 19, in <module>
    from config import ToolsConfig
ImportError: No module named 'config'

**Comment by MuhammadJamee** [comment]
You are missing files unfortunately, check lib/tools/     , if you see config.py file there

**Comment by Jet-A** [comment]
Having a similar issue. config.py exists.

**Error**
Traceback (most recent call last):
  File "tools.capture.py", line 9, in <module>
    from lib.tools.capture import ToolsCapture
  File "/home/pi/MagicMirror/modules/MMM-Facial-Recognition-OCV3/lib/tools/capture.py", line 10, in <module>
    from   builtins import input
ImportError: No module named builtins

**Comment by ezar** [comment]
same here!

**Comment by mhauens** [comment]
fixed it for me:

replace the line `from builtins import input` 
in 
`/home/pi/MagicMirror/modules/MMM-Facial-Recognition-OCV3/lib/tools/capture.py`
and in file
`/home/pi/MagicMirror/modules/MMM-Facial-Recognition-OCV3/tools.capture.py`
with
```python
import sys
if sys.version_info[0] < 3:
    import __builtin__ as builtins
else:
    import builtins
```

**Comment by wadewhitten** [comment]
I am still getting the error, even after editing the code @mhauens suggested. Any suggestions?

**Comment by nischi** [comment]
i have the same issue

**Comment by nischi** [comment]
okay for me it works if i use python3 instead of python

**Comment by SdeGeata** [comment]
Same error here:

`pi@raspberrypi:~/MagicMirror/modules/MMM-Facial-Recognition-OCV3 $ python tools.capture.py
Traceback (most recent call last):
  File "tools.capture.py", line 9, in <module>
    from lib.tools.capture import ToolsCapture
  File "/home/pi/MagicMirror/modules/MMM-Facial-Recognition-OCV3/lib/tools/capture.py", line 23, in <module>
    from config import ToolsConfig
ImportError: No module named 'config'
`

I have changed the "from builtins import input" lines as mhauens suggested, to no avail. Nothing works.

Nischi: How did you get it to work with Python3? Tried that too.

**Comment by SdeGeata** [comment]
I ended up fixing mine with this; in capture.py:

`from config import ToolsConfig -> from .config import ToolsConfig`
